# build-version: 185
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: urnr
  name: back
  labels:
    app: back
spec:
  # replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8082'
        prometheus.io/path: "/actuator/prometheus"
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: kjk7212/release_note_back:185
          imagePullPolicy: Always
          ports:
            - name: back
              containerPort: 8080
            - name: spring-actuator
              containerPort: 8082
          resources:
            limits:
              cpu: 750m
              memory: 2048Mi
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - back
              topologyKey: kubernetes.io/hostname
